### ISSUE TITLE
[BE] モジュールわけ

### ISSUE THREAD

**Issue by Terralien-jp** [Hackathon5-TeamD/evolution-quest#42]
blueprintを使用して以下のようにモジュールを分けようと思います。

* app.py
  * user.py
  * teminologie.py
  * result.py

* model.py

ごちゃごちゃしてきたらディレクトリ分けましょう

**Comment by Terralien-jp** [comment]
あーすでにmodel.pyがappディレクトリの中にある時点でおかしいなｗ

**Comment by Terralien-jp** [comment]
着手します！

**Comment by purewest-github** [comment]
Dockerの構成的にFlaskアプリは、appディレクトリ内になってます。
appディレクトリ外にロジックを置くのであれば修正します。

**Comment by Terralien-jp** [comment]
最新環境にマージして上げる予定！

**Comment by Terralien-jp** [comment]
大前提として現在のdevelopブランチは動きます。
つまりパーミッション問題はクリアされていると思われます。

その上で下記の手順を実施すると

## Flaskコンテナがコケる現象が発生
1. developからブランチを作成
2. pyファイルをコピーしてくる
3. ローカルで実行→うまくいく
4. コンテナを起動する→Flaskコンテナがコケる

コケたときに出るメッセージ
`Error: While importing 'app.app', an ImportError was raised.`
循環参照ではないかという内容らしいですが、構造見る限り起きていない模様

### 検証
前回問題となっていたローカルのrun.shパーミッションは755、コンテナの中身のパーミッションは777（？）

Exited(2)といういくら検索しても謎な原因で停止している。これは前回起きてた問題と同じです
`4b21ca4394c6   evolution-quest_flask   "bash -c ./run.sh"       11 minutes ago   Exited (2) 11 minutes ago`

* 相変わらずローカルでは動く
* モジュール分割してる部分をコメントアウトしapp.pyにルーティングを書くと、コンテナはコケず5001で動く
* コメントアウトしたままコンテナを起動し、コメントアウトを戻して接続すると動く

と言った感じで問題の切り分けができませんｗ
どなたか別環境で動かしてみてくださいませんか？

**Comment by Terralien-jp** [comment]
検証用にプルリクするのでよろしくお願いします！

**Comment by Terralien-jp** [comment]
上記とパーミッション問題を解決しました。
あとなんとなくmain.pyも切り出しましたｗ
