### ISSUE TITLE
[FE] サイドバー(ハンバーガーメニュー)　デザイン

### ISSUE THREAD

**Issue by Rinasham** [Hackathon5-TeamD/evolution-quest#49]
サイドバーコンポーネントのデザイン

#50

**Comment by Terralien-jp** [comment]
discussionにあったやつ動きがリッチですね！CSSの問題がクリアできればいいアイデアだと思います。

**Comment by Rinasham** [comment]
ものは試しで作ってみたのですがcodeSandBox上で拡張子をmodule.cssにすると読み込めないエラーが発生してるのでもう少しお待ちくださいw

**Comment by Terralien-jp** [comment]
ローカルでチェックしたほうが開発環境的には本番に近い可能性(?_?)
