### ISSUE TITLE
[FE]最優先ルーティング

### ISSUE THREAD

**Issue by Terralien-jp** [Hackathon5-TeamD/evolution-quest#51]
そういえば定例会でまずはコレ作らないと始まらないという話でしたｗ

**Comment by Terralien-jp** [comment]
開発用にすべてのリンクを一旦表示しておくなどでいかがでしょう？

**Comment by kobakichi** [comment]
コンポーネントは後で、ボタンだけ置いておくイメージでしょうか？

**Comment by Terralien-jp** [comment]
そうなりますね！コンポーネント作成時に追加していくでも構わないとは思いますが、開発時はこのような柔軟な対応ができると思います！まあ前回学んだことなのですがｗ

**Comment by kobakichi** [comment]
承知しました！
