### ISSUE TITLE
[FE]LoginページのCSSをApp.css→移動させる。&Loginページコンポーネントをpagesディレクトリへ移動。

### ISSUE THREAD

**Issue by kobakichi** [Hackathon5-TeamD/evolution-quest#66]
現状LoginページのみApp.cssへ記述してしまっているので、Loginページコンポーネントをpagesディレクトリへ移動させ、Module.cssへ変更する。

**Comment by Terralien-jp** [comment]
CSSについての方向性でちと決めねばならんことがありそうなのでこちらで話しますか！

## App.cssの影響強すぎ問題
統一カラーだよ！ということであればいいのですが、
bodyには何も指定しないという方向性はどうでしょうか？

対処方法として、
各コンポーネントのcss moduleで縦横100%のwrapperが指定されたdivタグ（レイヤー最上位もしくはID指定）を作りそれに`background-color`を当てるなど。

全部のコンポーネントでデザイン違うのか？などめんどくさいことも生じるので案の1つだということで検討してみてください。
私としてはこの案でゴリ押しなんて思いは1mmもなく、あくまで話し合いのたたき台としてあげた立場ですｗ
