### ISSUE TITLE
BE#2 userAPI

### ISSUE THREAD

**Issue by Terralien-jp** [Hackathon5-TeamD/evolution-quest#7]
API設計図に基づきuser APIの作成

https://docs.google.com/spreadsheets/d/1G2jgEe0a3wJ1hy8BUICf8oAxTeF6VnL-t__jTAnfHTM/edit#gid=322726659

- [x] ユーザー登録
- [x] ユーザー呼び出し

**Comment by daisuke-imamura** [comment]
#7-7 
userの呼び出し完了。
