### ISSUE TITLE
[解決…？]現在のDevelopで継続作業をしようとすると以下のエラーが出てnodeコンテナがコケる

### ISSUE THREAD

**Issue by Terralien-jp** [Hackathon5-TeamD/evolution-quest#71]
`Cannot find module '/front/node_modules/finalhandler/node_modules/debug/src/index.js'. Please verify that the package.json has a valid "main" entry`

エラーメッセージの通り、

`/front/node_modules/finalhandler/node_modules/debug/`

配下に`src/index.js`が存在しない問題が発生してしまいました

https://teamd-zwt3284.slack.com/archives/C03GJJ5A160/p1653809251625269

新規ディレクトリにてこちらの手順通り作成しております

**Comment by Terralien-jp** [comment]
https://www.npmjs.com/package/finalhandler

これは一体なんだろうｗ

**Comment by Terralien-jp** [comment]
## [原因]単なるミスｗ
`docker-compose-build.yml`実行してnode_modulesが完成する前に次の作業を行ったためｗ

> その後、コンテナ内でnpm installが終了すれば、コンテナは役目を終えて停止します。
この様子は、VScodeの拡張機能で「Docker Explorer」をインストールして、
左下の「DOCKER CONTAINERS」を見れば分かります。

この文章を3回読んで落ち着いて作業することで解決可能…ｗ

しばらくナレッジとして晒し上げた後にWikiにまとめときます！

**Comment by kobakichi** [comment]
💡

**Comment by Terralien-jp** [comment]
周知期間終了したのでクローズします！
