### ISSUE TITLE
[FE]ログインページロジック作成

### ISSUE THREAD

**Issue by Terralien-jp** [Hackathon5-TeamD/evolution-quest#88]
とりあえず形だけでも

**Comment by Rinasham** [comment]
formをサーバーに送信する＋入力が適切であるかとかそこら辺のロジックを書けばいいということですかね？

**Comment by Terralien-jp** [comment]
そうですね！
残念ながらバックエンドがまだ未着手なのでテストまでできれば御の字みたいな感じです。

**Comment by Rinasham** [comment]
了解です！
入力チェックに関してですが、どれぐらいの厳しさ(？)で判定すればいいでしょうか (´・∀・)?
これだけは絶対に入力時にチェックしてくれーな必須項目あったら教えてください

**Comment by Terralien-jp** [comment]
記号は使わないなどSQLインジェクション対策くらいでしょうかね(?_?)
セキュリティ関係はまだ体系的に学んでないので謎ですｗ

**Comment by Rinasham** [comment]
了解しましたー！
ちなみに認証には結局JWTを使うってことになったんでしたっけ...？（覚えてなくてすみません。汗）

**Comment by Terralien-jp** [comment]
そこまで話してなかった気もしますね？前回JWT使ったよってくらいで！
